In [9]:
import numpy as np

K=np.array([[0.2, 0.6, 0.2],
              [0.3, 0, 0.7],
              [0.5, 0, 0.5]])

eigenvalues, eigenvectors = np.linalg.eig(K)

# array([[ 0.83022467+0.j        ,  0.83022467+0.j        ],
#        [ 0.09133956+0.54989461j,  0.09133956-0.54989461j]])

eigenvectors.shape

(3, 3)

In [10]:
eigenvectors

array([[-0.57735027+0.j        , -0.70597631+0.j        ,
        -0.70597631-0.j        ],
       [-0.57735027+0.j        ,  0.26474112-0.4380559j ,
         0.26474112+0.4380559j ],
       [-0.57735027+0.j        ,  0.4412352 +0.21196253j,
         0.4412352 -0.21196253j]])

In [11]:
eigenvalues

array([ 1.  +0.j       , -0.15+0.3122499j, -0.15-0.3122499j])

In [20]:
import scipy.linalg as la

K=np.array([[0.2, 0.6, 0.2],
              [0.3, 0, 0.7],
              [0.5, 0, 0.5]])
w,vl,vr = la.eig(K,left=True)



In [16]:
vl

array([[-0.58746336+0.j        , -0.16984156-0.35355339j,
        -0.16984156+0.35355339j],
       [-0.35247801+0.j        ,  0.67936622+0.j        ,
         0.67936622-0.j        ],
       [-0.72845456+0.j        , -0.50952467+0.35355339j,
        -0.50952467-0.35355339j]])

In [17]:
vr

array([[-0.57735027+0.j        ,  0.70597631+0.j        ,
         0.70597631-0.j        ],
       [-0.57735027+0.j        , -0.26474112+0.4380559j ,
        -0.26474112-0.4380559j ],
       [-0.57735027+0.j        , -0.4412352 -0.21196253j,
        -0.4412352 +0.21196253j]])

In [18]:
w

array([ 1.  +0.j       , -0.15+0.3122499j, -0.15-0.3122499j])

In [23]:
A=np.array([[0.2, 0.6, 0.2],
              [0.3, 0, 0.7],
              [0.5, 0, 0.5]])
B=np.array([[0,1,0]])
result = np.dot(B,A)

array([[0.3, 0. , 0.7]])